tmux new-session -d -s session_3000 'python main.py --port 3000 --components alert --scenario_count 20'
tmux new-session -d -s session_3001 'python main.py --port 3001 --components bottom-navigation --scenario_count 20'
tmux new-session -d -s session_3002 'python main.py --port 3002 --components checkboxes --scenario_count 20'
tmux new-session -d -s session_3003 'python main.py --port 3003 --components drawers --scenario_count 20'
tmux new-session -d -s session_3004 'python main.py --port 3004 --components menus --scenario_count 20'
tmux new-session -d -s session_3005 'python main.py --port 3005 --components slider --scenario_count 20'
tmux new-session -d -s session_3006 'python main.py --port 3006 --components table --scenario_count 20'
tmux new-session -d -s session_3007 'python main.py --port 3007 --components tabs --scenario_count 20'
