python main_bbox.py --port 3001 --lib_name material --scenario_count 6
python main_bbox.py --port 3002 --lib_name material --scenario_count 6
python main_bbox.py --port 3003 --lib_name material --scenario_count 6
python main_bbox.py --port 3004 --lib_name material --scenario_count 6
python main_bbox.py --port 3005 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3006 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3007 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3008 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3009 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3010 --lib_name mantine --scenario_count 24
python main_bbox.py --port 3011 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3012 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3013 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3014 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3015 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3016 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3017 --lib_name material --scenario_count 6
python main_bbox.py --port 3018 --lib_name material --scenario_count 6
python main_bbox.py --port 3019 --lib_name material --scenario_count 6
python main_bbox.py --port 3020 --lib_name material --scenario_count 6
python main_bbox.py --port 3021 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3022 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3023 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3024 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3025 --lib_name chakra --scenario_count 5
python main_bbox.py --port 3026 --lib_name mantine --scenario_count 24
python main_bbox.py --port 3027 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3028 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3029 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3030 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3031 --lib_name ant-design --scenario_count 4
python main_bbox.py --port 3032 --lib_name ant-design --scenario_count 4

# pkill -f "python main_bbox.py"
