tmux new-session -d -s session_3000 'xvfb-run -a python main.py --port 3000 --components alert --scenario_count 2'
tmux new-session -d -s session_3001 'xvfb-run -a python main.py --port 3001 --components alert --scenario_count 2'
tmux new-session -d -s session_3002 'xvfb-run -a python main.py --port 3002 --components alert --scenario_count 2'
tmux new-session -d -s session_3003 'xvfb-run -a python main.py --port 3003 --components bottom-navigation --scenario_count 2'
tmux new-session -d -s session_3004 'xvfb-run -a python main.py --port 3004 --components bottom-navigation --scenario_count 2'
tmux new-session -d -s session_3005 'xvfb-run -a python main.py --port 3005 --components bottom-navigation --scenario_count 2'
tmux new-session -d -s session_3006 'xvfb-run -a python main.py --port 3006 --components checkboxes --scenario_count 2'
tmux new-session -d -s session_3007 'xvfb-run -a python main.py --port 3007 --components checkboxes --scenario_count 2'
tmux new-session -d -s session_3008 'xvfb-run -a python main.py --port 3008 --components checkboxes --scenario_count 2'
tmux new-session -d -s session_3009 'xvfb-run -a python main.py --port 3009 --components drawers --scenario_count 2'
tmux new-session -d -s session_3010 'xvfb-run -a python main.py --port 3010 --components drawers --scenario_count 2'
tmux new-session -d -s session_3011 'xvfb-run -a python main.py --port 3011 --components drawers --scenario_count 2'
tmux new-session -d -s session_3012 'xvfb-run -a python main.py --port 3012 --components menus --scenario_count 2'
tmux new-session -d -s session_3013 'xvfb-run -a python main.py --port 3013 --components menus --scenario_count 2'
tmux new-session -d -s session_3014 'xvfb-run -a python main.py --port 3014 --components menus --scenario_count 2'
tmux new-session -d -s session_3015 'xvfb-run -a python main.py --port 3015 --components slider --scenario_count 2'
tmux new-session -d -s session_3016 'xvfb-run -a python main.py --port 3016 --components slider --scenario_count 2'
tmux new-session -d -s session_3017 'xvfb-run -a python main.py --port 3017 --components slider --scenario_count 2'
tmux new-session -d -s session_3018 'xvfb-run -a python main.py --port 3018 --components table --scenario_count 2'
tmux new-session -d -s session_3019 'xvfb-run -a python main.py --port 3019 --components table --scenario_count 2'
tmux new-session -d -s session_3020 'xvfb-run -a python main.py --port 3020 --components table --scenario_count 2'
tmux new-session -d -s session_3021 'xvfb-run -a python main.py --port 3021 --components tabs --scenario_count 2'
tmux new-session -d -s session_3022 'xvfb-run -a python main.py --port 3022 --components tabs --scenario_count 2'
tmux new-session -d -s session_3023 'xvfb-run -a python main.py --port 3023 --components tabs --scenario_count 2'
tmux new-session -d -s session_3024 'xvfb-run -a python main.py --port 3024 --components app-bar --scenario_count 2'
tmux new-session -d -s session_3025 'xvfb-run -a python main.py --port 3025 --components app-bar --scenario_count 2'
tmux new-session -d -s session_3026 'xvfb-run -a python main.py --port 3026 --components app-bar --scenario_count 2'
tmux new-session -d -s session_3027 'xvfb-run -a python main.py --port 3027 --components chips --scenario_count 2'
tmux new-session -d -s session_3028 'xvfb-run -a python main.py --port 3028 --components chips --scenario_count 2'
tmux new-session -d -s session_3029 'xvfb-run -a python main.py --port 3029 --components chips --scenario_count 2'
tmux new-session -d -s session_3030 'xvfb-run -a python main.py --port 3030 --components dialogs --scenario_count 2'
tmux new-session -d -s session_3031 'xvfb-run -a python main.py --port 3031 --components dialogs --scenario_count 2'
tmux new-session -d -s session_3032 'xvfb-run -a python main.py --port 3032 --components dialogs --scenario_count 2'
tmux new-session -d -s session_3033 'xvfb-run -a python main.py --port 3033 --components lists --scenario_count 2'
tmux new-session -d -s session_3034 'xvfb-run -a python main.py --port 3034 --components lists --scenario_count 2'
tmux new-session -d -s session_3035 'xvfb-run -a python main.py --port 3035 --components lists --scenario_count 2'
tmux new-session -d -s session_3036 'xvfb-run -a python main.py --port 3036 --components rating --scenario_count 2'
tmux new-session -d -s session_3037 'xvfb-run -a python main.py --port 3037 --components rating --scenario_count 2'
tmux new-session -d -s session_3038 'xvfb-run -a python main.py --port 3038 --components rating --scenario_count 2'
tmux new-session -d -s session_3039 'xvfb-run -a python main.py --port 3039 --components snackbars speed-dial --scenario_count 2'
tmux new-session -d -s session_3040 'xvfb-run -a python main.py --port 3040 --components snackbars speed-dial --scenario_count 2'
tmux new-session -d -s session_3041 'xvfb-run -a python main.py --port 3041 --components snackbars speed-dial --scenario_count 2'
tmux new-session -d -s session_3042 'xvfb-run -a python main.py --port 3042 --components steppers switches --scenario_count 2'
tmux new-session -d -s session_3043 'xvfb-run -a python main.py --port 3043 --components steppers switches --scenario_count 2'
tmux new-session -d -s session_3044 'xvfb-run -a python main.py --port 3044 --components steppers switches --scenario_count 2'
tmux new-session -d -s session_3045 'xvfb-run -a python main.py --port 3045 --components toggle-button transfer-list --scenario_count 2'
tmux new-session -d -s session_3046 'xvfb-run -a python main.py --port 3046 --components toggle-button transfer-list --scenario_count 2'
tmux new-session -d -s session_3047 'xvfb-run -a python main.py --port 3047 --components toggle-button transfer-list --scenario_count 2'
