tmux new-session -d -s session_3001 'xvfb-run -a python main_bbox.py --port 3001 --components bottom-navigation --scenario_count 2 --api_type claude'
tmux new-session -d -s session_3002 'xvfb-run -a python main_bbox.py --port 3002 --components checkboxes --scenario_count 2 --api_type claude'
tmux new-session -d -s session_3003 'xvfb-run -a python main_bbox.py --port 3003 --components drawers --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3004 'xvfb-run -a python main_bbox.py --port 3004 --components menus --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3005 'xvfb-run -a python main_bbox.py --port 3005 --components slider --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3006 'xvfb-run -a python main_bbox.py --port 3006 --components table --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3007 'xvfb-run -a python main_bbox.py --port 3007 --components tabs --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3008 'xvfb-run -a python main_bbox.py --port 3008 --components app-bar --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3009 'xvfb-run -a python main_bbox.py --port 3009 --components chips --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3010 'xvfb-run -a python main_bbox.py --port 3010 --components dialogs --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3011 'xvfb-run -a python main_bbox.py --port 3011 --components lists --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3012 'xvfb-run -a python main_bbox.py --port 3012 --components rating --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3013 'xvfb-run -a python main_bbox.py --port 3013 --components snackbars speed-dial --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3014 'xvfb-run -a python main_bbox.py --port 3014 --components steppers switches --scenario_count 2 --api_type claude'
# tmux new-session -d -s session_3015 'xvfb-run -a python main_bbox.py --port 3015 --components toggle-button transfer-list --scenario_count 2 --api_type claude'
#tmux new-session -d -s session_3016 'xvfb-run -a python main_bbox.py --port 3000 --components alert --scenario_count 2 --api_type claude'
